// packages/r3f-vfx/src/VFXParticles.tsx
import {
  forwardRef,
  useImperativeHandle,
  useEffect,
  useRef,
  useMemo,
  useCallback,
  useState,
} from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import * as THREE from 'three/webgpu'
import { useVFXStore } from './react-store'
import {
  Appearance,
  Blending,
  EmitterShape,
  Lighting,
  VFXParticleSystem,
  isNonDefaultRotation,
  normalizeProps,
  updateUniforms,
  updateUniformsPartial,
  resolveFeatures,
  type VFXParticleSystemOptions,
} from 'core-vfx'

// Re-export constants and utilities for backwards compatibility
export {
  Appearance,
  Blending,
  EmitterShape,
  AttractorType,
  Easing,
  Lighting,
  bakeCurveToArray,
  createCombinedCurveTexture,
  buildCurveTextureBin,
  CurveChannel,
} from 'core-vfx'

export type { CurveTextureResult } from 'core-vfx'

export type VFXParticlesProps = VFXParticleSystemOptions & {
  /** Optional name for registering with useVFXStore (enables VFXEmitter linking) */
  name?: string
  /** Show debug control panel */
  debug?: boolean
}

export const VFXParticles = forwardRef<unknown, VFXParticlesProps>(
  function VFXParticles(
    {
      name,
      maxParticles = 10000,
      size = [0.1, 0.3],
      colorStart = ['#ffffff'],
      colorEnd = null,
      fadeSize = [1, 0],
      fadeSizeCurve = null,
      fadeOpacity = [1, 0],
      fadeOpacityCurve = null,
      velocityCurve = null,
      gravity = [0, 0, 0],
      lifetime = [1, 2],
      direction = [
        [-1, 1],
        [0, 1],
        [-1, 1],
      ],
      startPosition = [
        [0, 0],
        [0, 0],
        [0, 0],
      ],
      speed = [0.1, 0.1],
      friction = { intensity: 0, easing: 'linear' },
      appearance = Appearance.GRADIENT,
      alphaMap = null,
      flipbook = null,
      rotation = [0, 0],
      rotationSpeed = [0, 0],
      rotationSpeedCurve = null,
      geometry = null,
      orientToDirection = false,
      orientAxis = 'z',
      stretchBySpeed = null,
      lighting = Lighting.STANDARD,
      shadow = false,
      blending = Blending.NORMAL,
      intensity = 1,
      position = [0, 0, 0],
      autoStart = true,
      delay = 0,
      backdropNode = null,
      opacityNode = null,
      colorNode = null,
      alphaTestNode = null,
      castShadowNode = null,
      emitCount = 1,
      emitterShape = EmitterShape.BOX,
      emitterRadius = [0, 1],
      emitterAngle = Math.PI / 4,
      emitterHeight = [0, 1],
      emitterSurfaceOnly = false,
      emitterDirection = [0, 1, 0],
      turbulence = null,
      attractors = null,
      attractToCenter = false,
      startPositionAsDirection = false,
      softParticles = false,
      softDistance = 0.5,
      collision = null,
      debug = false,
      curveTexturePath = null,
      depthTest = true,
      renderOrder = 0,
    },
    ref
  ) {
    const { gl: renderer } = useThree()
    const spriteRef = useRef<THREE.Sprite | THREE.InstancedMesh | null>(null)
    const [emitting, setEmitting] = useState(autoStart)

    // State for "remount-required" values - changing these recreates GPU resources
    const [activeMaxParticles, setActiveMaxParticles] = useState(maxParticles)
    const [activeLighting, setActiveLighting] = useState(lighting)
    const [activeAppearance, setActiveAppearance] = useState(appearance)
    const [activeOrientToDirection, setActiveOrientToDirection] =
      useState(orientToDirection)
    const [activeGeometry, setActiveGeometry] = useState(geometry)
    const [activeShadow, setActiveShadow] = useState(shadow)
    const [activeFadeSizeCurve, setActiveFadeSizeCurve] =
      useState(fadeSizeCurve)
    const [activeFadeOpacityCurve, setActiveFadeOpacityCurve] =
      useState(fadeOpacityCurve)
    const [activeVelocityCurve, setActiveVelocityCurve] =
      useState(velocityCurve)
    const [activeRotationSpeedCurve, setActiveRotationSpeedCurve] =
      useState(rotationSpeedCurve)
    const [activeTurbulence, setActiveTurbulence] = useState(
      turbulence !== null && (turbulence?.intensity ?? 0) > 0
    )
    const [activeAttractors, setActiveAttractors] = useState(
      attractors !== null && attractors.length > 0
    )
    const [activeCollision, setActiveCollision] = useState(collision !== null)
    const [activeNeedsPerParticleColor, setActiveNeedsPerParticleColor] =
      useState(colorStart.length > 1 || colorEnd !== null)
    const [activeNeedsRotation, setActiveNeedsRotation] = useState(
      isNonDefaultRotation(rotation) || isNonDefaultRotation(rotationSpeed)
    )

    // Keep remount-required state in sync with props (when not in debug mode)
    useEffect(() => {
      if (!debug) {
        setActiveMaxParticles(maxParticles)
        setActiveLighting(lighting)
        setActiveAppearance(appearance)
        setActiveOrientToDirection(orientToDirection)
        setActiveGeometry(geometry)
        setActiveShadow(shadow)
        setActiveFadeSizeCurve(fadeSizeCurve)
        setActiveFadeOpacityCurve(fadeOpacityCurve)
        setActiveVelocityCurve(velocityCurve)
        setActiveRotationSpeedCurve(rotationSpeedCurve)
        setActiveNeedsPerParticleColor(
          colorStart.length > 1 || colorEnd !== null
        )
        setActiveNeedsRotation(
          isNonDefaultRotation(rotation) || isNonDefaultRotation(rotationSpeed)
        )
        setActiveTurbulence(
          turbulence !== null && (turbulence?.intensity ?? 0) > 0
        )
        setActiveAttractors(attractors !== null && attractors.length > 0)
        setActiveCollision(collision !== null)
      }
    }, [
      debug,
      maxParticles,
      lighting,
      appearance,
      orientToDirection,
      geometry,
      colorStart.length,
      colorEnd,
      shadow,
      fadeSizeCurve,
      fadeOpacityCurve,
      velocityCurve,
      rotationSpeedCurve,
      rotation,
      rotationSpeed,
      turbulence,
      attractors,
      collision,
    ])

    // Create/recreate system when structural props change
    const system = useMemo(
      () =>
        new VFXParticleSystem(
          renderer as unknown as THREE.WebGPURenderer,
          {
            maxParticles: activeMaxParticles,
            size,
            colorStart,
            colorEnd,
            fadeSize,
            fadeSizeCurve: activeFadeSizeCurve,
            fadeOpacity,
            fadeOpacityCurve: activeFadeOpacityCurve,
            velocityCurve: activeVelocityCurve,
            gravity,
            lifetime,
            direction,
            startPosition,
            speed,
            friction,
            appearance: activeAppearance,
            alphaMap,
            flipbook,
            rotation,
            rotationSpeed,
            rotationSpeedCurve: activeRotationSpeedCurve,
            geometry: activeGeometry,
            orientToDirection: activeOrientToDirection,
            orientAxis,
            stretchBySpeed,
            lighting: activeLighting,
            shadow: activeShadow,
            blending,
            intensity,
            position,
            autoStart,
            delay,
            emitCount,
            emitterShape,
            emitterRadius,
            emitterAngle,
            emitterHeight,
            emitterSurfaceOnly,
            emitterDirection,
            turbulence,
            attractors,
            attractToCenter,
            startPositionAsDirection,
            softParticles,
            softDistance,
            collision,
            backdropNode,
            opacityNode,
            colorNode,
            alphaTestNode,
            castShadowNode,
            depthTest,
            renderOrder,
            curveTexturePath,
          }
        ),
      // Only recreate when structural props change (features, maxParticles, etc.)
      // eslint-disable-next-line react-hooks/exhaustive-deps
      [
        renderer,
        activeMaxParticles,
        activeLighting,
        activeAppearance,
        activeOrientToDirection,
        activeGeometry,
        activeShadow,
        activeNeedsPerParticleColor,
        activeNeedsRotation,
        activeTurbulence,
        activeAttractors,
        activeCollision,
        activeFadeSizeCurve,
        activeFadeOpacityCurve,
        activeVelocityCurve,
        activeRotationSpeedCurve,
        alphaMap,
        flipbook,
        blending,
        backdropNode,
        opacityNode,
        colorNode,
        alphaTestNode,
        castShadowNode,
        softParticles,
        curveTexturePath,
      ]
    )

    // Initialize on mount
    useEffect(() => {
      system.init()
    }, [system])

    // Update uniforms when non-structural props change (skip in debug mode)
    useEffect(() => {
      if (debug) return

      system.setPosition(position)
      system.setDelay(delay)
      system.setEmitCount(emitCount)
      system.setTurbulenceSpeed(turbulence?.speed ?? 1)

      const normalized = normalizeProps({
        size,
        speed,
        fadeSize,
        fadeOpacity,
        lifetime,
        gravity,
        direction,
        startPosition,
        rotation,
        rotationSpeed,
        friction,
        intensity,
        colorStart,
        colorEnd,
        emitterShape,
        emitterRadius,
        emitterAngle,
        emitterHeight,
        emitterSurfaceOnly,
        emitterDirection,
        turbulence,
        attractors,
        attractToCenter,
        startPositionAsDirection,
        softParticles,
        softDistance,
        collision,
        orientAxis,
        stretchBySpeed,
      })
      updateUniforms(system.uniforms, normalized)
    }, [
      debug,
      system,
      position,
      size,
      fadeSize,
      fadeOpacity,
      gravity,
      friction,
      speed,
      lifetime,
      direction,
      rotation,
      rotationSpeed,
      intensity,
      colorStart,
      colorEnd,
      collision,
      emitterShape,
      emitterRadius,
      emitterAngle,
      emitterHeight,
      emitterSurfaceOnly,
      emitterDirection,
      turbulence,
      startPosition,
      attractors,
      attractToCenter,
      startPositionAsDirection,
      softParticles,
      softDistance,
      orientAxis,
      stretchBySpeed,
      delay,
      emitCount,
    ])

    // Public spawn - uses system position as offset, supports overrides
    const spawn = useCallback(
      (
        x = 0,
        y = 0,
        z = 0,
        count = 20,
        overrides: Record<string, unknown> | null = null
      ) => {
        const [px, py, pz] = system.position
        system.spawn(px + x, py + y, pz + z, count, overrides)
      },
      [system]
    )

    // Update each frame + auto emit
    useFrame(async (_state, delta) => {
      if (!system.initialized) return

      await system.update(delta)

      if (emitting) {
        system.autoEmit(delta)
      }
    })

    // Start/stop functions
    const start = useCallback(() => {
      system.start()
      setEmitting(true)
    }, [system])

    const stop = useCallback(() => {
      system.stop()
      setEmitting(false)
    }, [system])

    // Cleanup old material/renderObject when they change (not on unmount)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const prevMaterialRef = useRef<any>(null)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const prevRenderObjectRef = useRef<any>(null)

    useEffect(() => {
      // Dispose previous material if it changed
      if (
        prevMaterialRef.current &&
        prevMaterialRef.current !== system.material
      ) {
        prevMaterialRef.current.dispose()
      }
      prevMaterialRef.current = system.material

      // Dispose previous renderObject if it changed
      if (
        prevRenderObjectRef.current &&
        prevRenderObjectRef.current !== system.renderObject
      ) {
        if (prevRenderObjectRef.current.material) {
          prevRenderObjectRef.current.material.dispose()
        }
      }
      prevRenderObjectRef.current = system.renderObject
    }, [system.material, system.renderObject])

    // Cleanup on actual unmount only
    useEffect(() => {
      return () => {
        system.dispose()
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    // Expose methods via ref
    const particleAPI = useMemo(
      () => ({
        spawn,
        start,
        stop,
        get isEmitting() {
          return emitting
        },
        clear() {
          system.clear()
        },
        uniforms: system.uniforms,
      }),
      [spawn, start, stop, emitting, system]
    )

    useImperativeHandle(ref, () => particleAPI, [particleAPI])

    // Register with VFX store when name prop is provided
    const registerParticles = useVFXStore((s) => s.registerParticles)
    const unregisterParticles = useVFXStore((s) => s.unregisterParticles)

    useEffect(() => {
      if (!name) return

      registerParticles(name, particleAPI)

      return () => {
        unregisterParticles(name)
      }
    }, [name, particleAPI, registerParticles, unregisterParticles])

    // Debug panel - no React state, direct ref mutation
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const debugValuesRef = useRef<any>(null)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const prevGeometryTypeRef = useRef<any>(null)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const prevGeometryArgsRef = useRef<any>(null)

    // Imperative update function called by debug panel
    const handleDebugUpdate = useCallback(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (newValues: any) => {
        // Merge new values into existing (dirty tracking only sends changed keys)
        debugValuesRef.current = { ...debugValuesRef.current, ...newValues }

        // Handle colorStart→colorEnd fallback before calling core
        // When colorStart changes and colorEnd is null, sync colorEnd uniforms
        if ('colorStart' in newValues && newValues.colorStart) {
          const currentColorEnd = debugValuesRef.current?.colorEnd
          if (!currentColorEnd) {
            // Pass colorStart as colorEnd so updateUniformsPartial handles both
            newValues = {
              ...newValues,
              colorEnd: null,
            }
          }
        }
        // For colorEnd, resolve fallback to colorStart
        if ('colorEnd' in newValues && !newValues.colorEnd) {
          newValues = {
            ...newValues,
            colorEnd: null,
            // Ensure updateUniformsPartial gets the right fallback
            colorStart: newValues.colorStart ??
              debugValuesRef.current?.colorStart ?? ['#ffffff'],
          }
        }

        // Update all uniform values via core function
        updateUniformsPartial(system.uniforms, newValues)

        // React state: curves (trigger recreation)
        if ('fadeSizeCurve' in newValues) {
          setActiveFadeSizeCurve(newValues.fadeSizeCurve)
        }
        if ('fadeOpacityCurve' in newValues) {
          setActiveFadeOpacityCurve(newValues.fadeOpacityCurve)
        }
        if ('velocityCurve' in newValues) {
          setActiveVelocityCurve(newValues.velocityCurve)
        }
        if ('rotationSpeedCurve' in newValues) {
          setActiveRotationSpeedCurve(newValues.rotationSpeedCurve)
        }

        // Update turbulence speed on system
        if ('turbulence' in newValues) {
          system.setTurbulenceSpeed(newValues.turbulence?.speed ?? 1)
        }

        // React state: feature flags that trigger recreation
        const newFeatures = resolveFeatures(debugValuesRef.current)
        if (newFeatures.needsRotation !== activeNeedsRotation) {
          setActiveNeedsRotation(newFeatures.needsRotation)
        }
        if (newFeatures.needsPerParticleColor !== activeNeedsPerParticleColor) {
          setActiveNeedsPerParticleColor(newFeatures.needsPerParticleColor)
        }
        if (newFeatures.turbulence !== activeTurbulence) {
          setActiveTurbulence(newFeatures.turbulence)
        }
        if (newFeatures.attractors !== activeAttractors) {
          setActiveAttractors(newFeatures.attractors)
        }
        if (newFeatures.collision !== activeCollision) {
          setActiveCollision(newFeatures.collision)
        }

        // Position update
        if (newValues.position) {
          system.setPosition(newValues.position)
        }

        // Runtime updates
        if ('delay' in newValues) system.setDelay(newValues.delay ?? 0)
        if ('emitCount' in newValues)
          system.setEmitCount(newValues.emitCount ?? 1)

        // Update emitting state
        if (newValues.autoStart !== undefined) {
          setEmitting(newValues.autoStart)
        }

        // Update material blending directly
        if (system.material && newValues.blending !== undefined) {
          system.material.blending = newValues.blending
          system.material.needsUpdate = true
        }

        // Remount-required values
        if (
          newValues.maxParticles !== undefined &&
          newValues.maxParticles !== activeMaxParticles
        ) {
          setActiveMaxParticles(newValues.maxParticles)
          system.initialized = false
          system.nextIndex = 0
        }
        if (
          newValues.lighting !== undefined &&
          newValues.lighting !== activeLighting
        ) {
          setActiveLighting(newValues.lighting)
        }
        if (
          newValues.appearance !== undefined &&
          newValues.appearance !== activeAppearance
        ) {
          setActiveAppearance(newValues.appearance)
        }
        if (
          newValues.orientToDirection !== undefined &&
          newValues.orientToDirection !== activeOrientToDirection
        ) {
          setActiveOrientToDirection(newValues.orientToDirection)
        }
        if (
          newValues.shadow !== undefined &&
          newValues.shadow !== activeShadow
        ) {
          setActiveShadow(newValues.shadow)
        }

        // Handle geometry type and args changes
        if ('geometryType' in newValues || 'geometryArgs' in newValues) {
          const geoType = newValues.geometryType ?? prevGeometryTypeRef.current
          const geoArgs = newValues.geometryArgs ?? prevGeometryArgsRef.current
          const geoTypeChanged =
            'geometryType' in newValues &&
            geoType !== prevGeometryTypeRef.current
          const geoArgsChanged =
            'geometryArgs' in newValues &&
            JSON.stringify(geoArgs) !==
              JSON.stringify(prevGeometryArgsRef.current)

          if (geoTypeChanged || geoArgsChanged) {
            prevGeometryTypeRef.current = geoType
            prevGeometryArgsRef.current = geoArgs

            import('debug-vfx').then(({ createGeometry, GeometryType }) => {
              if (geoType === GeometryType.NONE || !geoType) {
                if (activeGeometry !== null && !geometry) {
                  activeGeometry.dispose()
                }
                setActiveGeometry(null)
              } else {
                const newGeometry = createGeometry(geoType, geoArgs)
                if (newGeometry) {
                  if (activeGeometry !== null && activeGeometry !== geometry) {
                    activeGeometry.dispose()
                  }
                  setActiveGeometry(newGeometry)
                }
              }
            })
          }
        }
      },
      [
        system,
        activeMaxParticles,
        activeLighting,
        activeAppearance,
        activeOrientToDirection,
        activeShadow,
        activeGeometry,
        activeNeedsPerParticleColor,
        activeNeedsRotation,
        activeTurbulence,
        activeAttractors,
        activeCollision,
        geometry,
      ]
    )

    // Initialize debug panel once on mount if debug is enabled
    useEffect(() => {
      if (!debug) return

      import('debug-vfx').then(
        ({ renderDebugPanel, detectGeometryTypeAndArgs }) => {
          const initialValues = {
            name,
            maxParticles,
            size,
            colorStart,
            colorEnd,
            fadeSize,
            fadeSizeCurve: fadeSizeCurve || null,
            fadeOpacity,
            fadeOpacityCurve: fadeOpacityCurve || null,
            velocityCurve: velocityCurve || null,
            gravity,
            lifetime,
            direction,
            startPosition,
            startPositionAsDirection,
            speed,
            friction,
            appearance,
            rotation,
            rotationSpeed,
            rotationSpeedCurve: rotationSpeedCurve || null,
            orientToDirection,
            orientAxis,
            stretchBySpeed: stretchBySpeed || null,
            lighting,
            shadow,
            blending,
            intensity,
            position,
            autoStart,
            delay,
            emitCount,
            emitterShape,
            emitterRadius,
            emitterAngle,
            emitterHeight,
            emitterSurfaceOnly,
            emitterDirection,
            turbulence,
            attractToCenter,
            softParticles,
            softDistance,
            collision,
            ...detectGeometryTypeAndArgs(geometry),
          }

          debugValuesRef.current = initialValues
          prevGeometryTypeRef.current = initialValues.geometryType
          prevGeometryArgsRef.current = initialValues.geometryArgs

          renderDebugPanel(initialValues, handleDebugUpdate)
        }
      )

      return () => {
        import('debug-vfx').then(({ destroyDebugPanel }) => {
          destroyDebugPanel()
        })
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [debug, geometry])

    // Update debug panel callback when handleDebugUpdate changes
    useEffect(() => {
      if (!debug) return
      import('debug-vfx').then(({ updateDebugPanel }) => {
        if (debugValuesRef.current) {
          updateDebugPanel({ ...debugValuesRef.current }, handleDebugUpdate)
        }
      })
    }, [debug, handleDebugUpdate])

    // @ts-expect-error
    return <primitive ref={spriteRef} object={system.renderObject} />
  }
)

// packages/threlte-vfx/src/VFXParticles.svelte
<script lang="ts">
import { T, useThrelte, useTask } from '@threlte/core'
import { onMount, onDestroy, untrack } from 'svelte'
import * as THREE from 'three/webgpu'
import { coreStore } from 'core-vfx'
import {
  Appearance,
  Blending,
  EmitterShape,
  Lighting,
  VFXParticleSystem,
  isNonDefaultRotation,
  normalizeProps,
  updateUniforms,
  updateUniformsPartial,
  resolveFeatures,
  type VFXParticleSystemOptions,
  type TurbulenceConfig,
  type AttractorConfig,
  type CollisionConfig,
  type FrictionConfig,
  type FlipbookConfig,
  type StretchConfig,
  type Rotation3DInput,
} from 'core-vfx'

// Props
let {
  name = undefined,
  debug = false,
  maxParticles = 10000,
  size = [0.1, 0.3],
  colorStart = ['#ffffff'],
  colorEnd = null,
  fadeSize = [1, 0],
  fadeSizeCurve = null,
  fadeOpacity = [1, 0],
  fadeOpacityCurve = null,
  velocityCurve = null,
  gravity = [0, 0, 0],
  lifetime = [1, 2],
  direction = [[-1, 1], [0, 1], [-1, 1]],
  startPosition = [[0, 0], [0, 0], [0, 0]],
  speed = [0.1, 0.1],
  friction = { intensity: 0, easing: 'linear' },
  appearance = Appearance.GRADIENT,
  alphaMap = null,
  flipbook = null,
  rotation = [0, 0],
  rotationSpeed = [0, 0],
  rotationSpeedCurve = null,
  geometry = null,
  orientToDirection = false,
  orientAxis = 'z',
  stretchBySpeed = null,
  lighting = Lighting.STANDARD,
  shadow = false,
  blending = Blending.NORMAL,
  intensity = 1,
  position = [0, 0, 0],
  autoStart = true,
  delay = 0,
  backdropNode = null,
  opacityNode = null,
  colorNode = null,
  alphaTestNode = null,
  castShadowNode = null,
  emitCount = 1,
  emitterShape = EmitterShape.BOX,
  emitterRadius = [0, 1],
  emitterAngle = Math.PI / 4,
  emitterHeight = [0, 1],
  emitterSurfaceOnly = false,
  emitterDirection = [0, 1, 0],
  turbulence = null,
  attractors = null,
  attractToCenter = false,
  startPositionAsDirection = false,
  softParticles = false,
  softDistance = 0.5,
  collision = null,
  curveTexturePath = null,
  depthTest = true,
  renderOrder = 0,
}: {
  name?: string
  debug?: boolean
  maxParticles?: number
  size?: [number, number] | number
  colorStart?: string[]
  colorEnd?: string[] | null
  fadeSize?: [number, number]
  fadeSizeCurve?: unknown[] | null
  fadeOpacity?: [number, number]
  fadeOpacityCurve?: unknown[] | null
  velocityCurve?: unknown[] | null
  gravity?: [number, number, number]
  lifetime?: [number, number]
  direction?: VFXParticleSystemOptions['direction']
  startPosition?: VFXParticleSystemOptions['startPosition']
  speed?: [number, number] | number
  friction?: FrictionConfig
  appearance?: string | number
  alphaMap?: THREE.Texture | null
  flipbook?: FlipbookConfig | null
  rotation?: Rotation3DInput
  rotationSpeed?: Rotation3DInput
  rotationSpeedCurve?: unknown[] | null
  geometry?: THREE.BufferGeometry | null
  orientToDirection?: boolean
  orientAxis?: string
  stretchBySpeed?: StretchConfig | null
  lighting?: string | number
  shadow?: boolean
  blending?: string | number
  intensity?: number
  position?: [number, number, number]
  autoStart?: boolean
  delay?: number
  backdropNode?: unknown
  opacityNode?: unknown
  colorNode?: unknown
  alphaTestNode?: unknown
  castShadowNode?: unknown
  emitCount?: number
  emitterShape?: string | number
  emitterRadius?: [number, number]
  emitterAngle?: number
  emitterHeight?: [number, number]
  emitterSurfaceOnly?: boolean
  emitterDirection?: [number, number, number]
  turbulence?: TurbulenceConfig | null
  attractors?: AttractorConfig[] | null
  attractToCenter?: boolean
  startPositionAsDirection?: boolean
  softParticles?: boolean
  softDistance?: number
  collision?: CollisionConfig | null
  curveTexturePath?: string | null
  depthTest?: boolean
  renderOrder?: number
} = $props()

const { renderer } = useThrelte()

let mounted = false

// Internal state — NOT tracked by effects (plain variables)
let _system: VFXParticleSystem | null = null
let _renderObject: THREE.Object3D | null = null
let _emitting = autoStart

// Reactive state for the template only
let renderObjectForTemplate: THREE.Object3D | null = $state(null)

let debugValues: Record<string, unknown> | null = null

// Track structural props for recreation
let activeMaxParticles = $state(maxParticles)
let activeLighting: string | number = $state(lighting)
let activeAppearance: string | number = $state(appearance)
let activeOrientToDirection = $state(orientToDirection)
let activeGeometry: THREE.BufferGeometry | null = $state(geometry)
let activeShadow = $state(shadow)
let activeFadeSizeCurve: unknown[] | null = $state(fadeSizeCurve)
let activeFadeOpacityCurve: unknown[] | null = $state(fadeOpacityCurve)
let activeVelocityCurve: unknown[] | null = $state(velocityCurve)
let activeRotationSpeedCurve: unknown[] | null = $state(rotationSpeedCurve)
let activeTurbulence = $state(
  turbulence !== null && (turbulence?.intensity ?? 0) > 0
)
let activeAttractors = $state(
  attractors !== null && (attractors?.length ?? 0) > 0
)
let activeCollision = $state(collision !== null)
let activeNeedsPerParticleColor = $state(
  colorStart.length > 1 || colorEnd !== null
)
let activeNeedsRotation = $state(
  isNonDefaultRotation(rotation) || isNonDefaultRotation(rotationSpeed)
)

// Debug panel refs
let prevGeometryType: unknown = null
let prevGeometryArgs: unknown = null

function buildOptions(): VFXParticleSystemOptions {
  const dbg = debug ? debugValues : null
  return {
    maxParticles: untrack(() => activeMaxParticles) as number,
    size: (dbg?.size ?? size) as VFXParticleSystemOptions['size'],
    colorStart: (dbg?.colorStart ?? colorStart) as string[],
    colorEnd:
      dbg?.colorEnd !== undefined
        ? (dbg.colorEnd as string[] | null)
        : colorEnd,
    fadeSize: (dbg?.fadeSize ?? fadeSize) as [number, number],
    fadeSizeCurve: untrack(() => activeFadeSizeCurve) as VFXParticleSystemOptions['fadeSizeCurve'],
    fadeOpacity: (dbg?.fadeOpacity ?? fadeOpacity) as [number, number],
    fadeOpacityCurve: untrack(() => activeFadeOpacityCurve) as VFXParticleSystemOptions['fadeOpacityCurve'],
    velocityCurve: untrack(() => activeVelocityCurve) as VFXParticleSystemOptions['velocityCurve'],
    gravity: (dbg?.gravity ?? gravity) as [number, number, number],
    lifetime: (dbg?.lifetime ?? lifetime) as [number, number],
    direction: (dbg?.direction ?? direction) as VFXParticleSystemOptions['direction'],
    startPosition: (dbg?.startPosition ?? startPosition) as VFXParticleSystemOptions['startPosition'],
    speed: (dbg?.speed ?? speed) as VFXParticleSystemOptions['speed'],
    friction: (dbg?.friction ?? friction) as FrictionConfig,
    appearance: untrack(() => activeAppearance) as VFXParticleSystemOptions['appearance'],
    alphaMap,
    flipbook,
    rotation: (dbg?.rotation ?? rotation) as Rotation3DInput,
    rotationSpeed: (dbg?.rotationSpeed ?? rotationSpeed) as Rotation3DInput,
    rotationSpeedCurve: untrack(() => activeRotationSpeedCurve) as VFXParticleSystemOptions['rotationSpeedCurve'],
    geometry: untrack(() => activeGeometry),
    orientToDirection: untrack(() => activeOrientToDirection) as boolean,
    orientAxis: (dbg?.orientAxis ?? orientAxis) as string,
    stretchBySpeed: (dbg?.stretchBySpeed ?? stretchBySpeed) as StretchConfig | null,
    lighting: untrack(() => activeLighting) as VFXParticleSystemOptions['lighting'],
    shadow: untrack(() => activeShadow) as boolean,
    blending: (dbg?.blending ?? blending) as VFXParticleSystemOptions['blending'],
    intensity: (dbg?.intensity ?? intensity) as number,
    position: (dbg?.position ?? position) as [number, number, number],
    autoStart: (dbg?.autoStart ?? autoStart) as boolean,
    delay: (dbg?.delay ?? delay) as number,
    emitCount: (dbg?.emitCount ?? emitCount) as number,
    emitterShape: (dbg?.emitterShape ?? emitterShape) as VFXParticleSystemOptions['emitterShape'],
    emitterRadius: (dbg?.emitterRadius ?? emitterRadius) as [number, number],
    emitterAngle: (dbg?.emitterAngle ?? emitterAngle) as number,
    emitterHeight: (dbg?.emitterHeight ?? emitterHeight) as [number, number],
    emitterSurfaceOnly: (dbg?.emitterSurfaceOnly ?? emitterSurfaceOnly) as boolean,
    emitterDirection: (dbg?.emitterDirection ?? emitterDirection) as [number, number, number],
    turbulence: (dbg?.turbulence ?? turbulence) as TurbulenceConfig | null,
    attractors: (dbg?.attractors ?? attractors) as AttractorConfig[] | null,
    attractToCenter: (dbg?.attractToCenter ?? attractToCenter) as boolean,
    startPositionAsDirection: (dbg?.startPositionAsDirection ?? startPositionAsDirection) as boolean,
    softParticles: (dbg?.softParticles ?? softParticles) as boolean,
    softDistance: (dbg?.softDistance ?? softDistance) as number,
    collision: (dbg?.collision ?? collision) as CollisionConfig | null,
    backdropNode: backdropNode as VFXParticleSystemOptions['backdropNode'],
    opacityNode: opacityNode as VFXParticleSystemOptions['opacityNode'],
    colorNode: colorNode as VFXParticleSystemOptions['colorNode'],
    alphaTestNode: alphaTestNode as VFXParticleSystemOptions['alphaTestNode'],
    castShadowNode: castShadowNode as VFXParticleSystemOptions['castShadowNode'],
    depthTest: (dbg?.depthTest ?? depthTest) as boolean,
    renderOrder: (dbg?.renderOrder ?? renderOrder) as number,
    curveTexturePath,
  }
}

function createSystem() {
  const r = renderer as unknown as THREE.WebGPURenderer
  if (!r) return null
  return new VFXParticleSystem(r, buildOptions())
}

function destroySystem() {
  if (!_system) return
  if (name) {
    coreStore.getState().unregisterParticles(name)
  }
  _system.dispose()
  _system = null
  _renderObject = null
  renderObjectForTemplate = null
}

function initSystem() {
  const oldSystem = _system
  if (oldSystem) {
    oldSystem.initialized = false
    if (name) {
      coreStore.getState().unregisterParticles(name)
    }
  }
  _system = null
  _renderObject = null

  if (!renderer) {
    console.warn('threlte-vfx: No renderer instance available')
    return
  }

  const newSystem = createSystem()
  if (!newSystem) return

  _system = newSystem
  _renderObject = newSystem.renderObject

  newSystem.init()

  if (name) {
    coreStore.getState().registerParticles(name, {
      spawn: (x = 0, y = 0, z = 0, count = 20, overrides = null) => {
        const [px, py, pz] = newSystem.position
        newSystem.spawn(px + x, py + y, pz + z, count, overrides)
      },
      start: () => {
        newSystem.start()
        _emitting = true
      },
      stop: () => {
        newSystem.stop()
        _emitting = false
      },
      get isEmitting() {
        return _emitting
      },
      clear: () => newSystem.clear(),
      uniforms: newSystem.uniforms,
    })
  }

  if (debug) {
    initDebugPanel()
  }

  // Update template-facing reactive state last
  renderObjectForTemplate = newSystem.renderObject
}

// Debug panel support
function handleDebugUpdate(newValues: Record<string, unknown>) {
  debugValues = { ...debugValues, ...newValues }
  if (!_system) return

  if ('colorStart' in newValues && newValues.colorStart) {
    const currentColorEnd = debugValues?.colorEnd
    if (!currentColorEnd) {
      newValues = { ...newValues, colorEnd: null }
    }
  }
  if ('colorEnd' in newValues && !newValues.colorEnd) {
    newValues = {
      ...newValues,
      colorEnd: null,
      colorStart:
        newValues.colorStart ??
        debugValues?.colorStart ?? ['#ffffff'],
    }
  }

  updateUniformsPartial(_system.uniforms, newValues)

  if ('fadeSizeCurve' in newValues) {
    activeFadeSizeCurve = newValues.fadeSizeCurve as unknown[] | null
  }
  if ('fadeOpacityCurve' in newValues) {
    activeFadeOpacityCurve = newValues.fadeOpacityCurve as unknown[] | null
  }
  if ('velocityCurve' in newValues) {
    activeVelocityCurve = newValues.velocityCurve as unknown[] | null
  }
  if ('rotationSpeedCurve' in newValues) {
    activeRotationSpeedCurve = newValues.rotationSpeedCurve as unknown[] | null
  }

  if ('turbulence' in newValues) {
    _system.setTurbulenceSpeed(
      (newValues.turbulence as TurbulenceConfig | null)?.speed ?? 1
    )
  }

  const newFeatures = resolveFeatures(
    debugValues as Record<string, unknown>
  )
  if (newFeatures.needsRotation !== activeNeedsRotation) {
    activeNeedsRotation = newFeatures.needsRotation
  }
  if (newFeatures.needsPerParticleColor !== activeNeedsPerParticleColor) {
    activeNeedsPerParticleColor = newFeatures.needsPerParticleColor
  }
  if (newFeatures.turbulence !== activeTurbulence) {
    activeTurbulence = newFeatures.turbulence
  }
  if (newFeatures.attractors !== activeAttractors) {
    activeAttractors = newFeatures.attractors
  }
  if (newFeatures.collision !== activeCollision) {
    activeCollision = newFeatures.collision
  }

  if (newValues.position) {
    _system.setPosition(newValues.position as [number, number, number])
  }

  if ('delay' in newValues) _system.setDelay((newValues.delay as number) ?? 0)
  if ('emitCount' in newValues)
    _system.setEmitCount((newValues.emitCount as number) ?? 1)

  if (newValues.autoStart !== undefined) {
    _emitting = newValues.autoStart as boolean
  }

  if (_system.material && newValues.blending !== undefined) {
    ;(_system.material as any).blending = newValues.blending
    ;(_system.material as any).needsUpdate = true
  }

  if (
    newValues.maxParticles !== undefined &&
    newValues.maxParticles !== activeMaxParticles
  ) {
    activeMaxParticles = newValues.maxParticles as number
    _system.initialized = false
    _system.nextIndex = 0
  }
  if (
    newValues.lighting !== undefined &&
    newValues.lighting !== activeLighting
  ) {
    activeLighting = newValues.lighting as string | number
  }
  if (
    newValues.appearance !== undefined &&
    newValues.appearance !== activeAppearance
  ) {
    activeAppearance = newValues.appearance as string | number
  }
  if (
    newValues.orientToDirection !== undefined &&
    newValues.orientToDirection !== activeOrientToDirection
  ) {
    activeOrientToDirection = newValues.orientToDirection as boolean
  }
  if (
    newValues.shadow !== undefined &&
    newValues.shadow !== activeShadow
  ) {
    activeShadow = newValues.shadow as boolean
  }

  if ('geometryType' in newValues || 'geometryArgs' in newValues) {
    const geoType =
      newValues.geometryType ?? prevGeometryType
    const geoArgs =
      newValues.geometryArgs ?? prevGeometryArgs
    const geoTypeChanged =
      'geometryType' in newValues &&
      geoType !== prevGeometryType
    const geoArgsChanged =
      'geometryArgs' in newValues &&
      JSON.stringify(geoArgs) !==
        JSON.stringify(prevGeometryArgs)

    if (geoTypeChanged || geoArgsChanged) {
      prevGeometryType = geoType
      prevGeometryArgs = geoArgs

      import('debug-vfx').then((mod) => {
        const { createGeometry, GeometryType } = mod
        if (geoType === GeometryType.NONE || !geoType) {
          if (activeGeometry !== null && !geometry) {
            activeGeometry.dispose()
          }
          activeGeometry = null
        } else {
          const newGeometry = createGeometry(geoType as string, geoArgs as Record<string, number> | undefined)
          if (newGeometry) {
            if (
              activeGeometry !== null &&
              activeGeometry !== geometry
            ) {
              activeGeometry.dispose()
            }
            activeGeometry = newGeometry
          }
        }
      })
    }
  }
}

function initDebugPanel() {
  import('debug-vfx').then((mod) => {
    const { renderDebugPanel, detectGeometryTypeAndArgs } = mod

    if (!debugValues) {
      const initialValues: Record<string, unknown> = {
        name,
        maxParticles,
        size,
        colorStart,
        colorEnd,
        fadeSize,
        fadeSizeCurve: fadeSizeCurve || null,
        fadeOpacity,
        fadeOpacityCurve: fadeOpacityCurve || null,
        velocityCurve: velocityCurve || null,
        gravity,
        lifetime,
        direction,
        startPosition,
        startPositionAsDirection,
        speed,
        friction,
        appearance,
        rotation,
        rotationSpeed,
        rotationSpeedCurve: rotationSpeedCurve || null,
        orientToDirection,
        orientAxis,
        stretchBySpeed: stretchBySpeed || null,
        lighting,
        shadow,
        blending,
        intensity,
        position,
        autoStart,
        delay,
        emitCount,
        emitterShape,
        emitterRadius,
        emitterAngle,
        emitterHeight,
        emitterSurfaceOnly,
        emitterDirection,
        turbulence,
        attractToCenter,
        softParticles,
        softDistance,
        collision,
        ...detectGeometryTypeAndArgs(geometry),
      }

      debugValues = initialValues
      prevGeometryType = initialValues.geometryType
      prevGeometryArgs = initialValues.geometryArgs
    }

    renderDebugPanel(debugValues, handleDebugUpdate, 'threlte')
  })
}

// Watch structural props for recreation (skip in debug mode)
$effect(() => {
  // Read all structural props to track them
  const _deps = [
    maxParticles,
    lighting,
    appearance,
    orientToDirection,
    geometry,
    shadow,
    fadeSizeCurve,
    fadeOpacityCurve,
    velocityCurve,
    rotationSpeedCurve,
    colorStart.length,
    colorEnd,
    rotation,
    rotationSpeed,
    turbulence,
    attractors,
    collision,
  ]

  if (debug) return

  // Use untrack for writes to avoid circular dependencies
  untrack(() => {
    activeMaxParticles = maxParticles
    activeLighting = lighting
    activeAppearance = appearance
    activeOrientToDirection = orientToDirection
    activeGeometry = geometry
    activeShadow = shadow
    activeFadeSizeCurve = fadeSizeCurve
    activeFadeOpacityCurve = fadeOpacityCurve
    activeVelocityCurve = velocityCurve
    activeRotationSpeedCurve = rotationSpeedCurve
    activeNeedsPerParticleColor =
      colorStart.length > 1 || colorEnd !== null
    activeNeedsRotation =
      isNonDefaultRotation(rotation) ||
      isNonDefaultRotation(rotationSpeed)
    activeTurbulence =
      turbulence !== null && (turbulence?.intensity ?? 0) > 0
    activeAttractors =
      attractors !== null && (attractors?.length ?? 0) > 0
    activeCollision = collision !== null
  })
})

// Watch structural active values for system recreation
$effect(() => {
  // Read all active values to track them
  const _deps = [
    activeMaxParticles,
    activeLighting,
    activeAppearance,
    activeOrientToDirection,
    activeGeometry,
    activeShadow,
    activeNeedsPerParticleColor,
    activeNeedsRotation,
    activeTurbulence,
    activeAttractors,
    activeCollision,
    activeFadeSizeCurve,
    activeFadeOpacityCurve,
    activeVelocityCurve,
    activeRotationSpeedCurve,
  ]

  if (!mounted) return

  // Use untrack for the actual init to avoid reading/writing
  // reactive state that would re-trigger this effect
  untrack(() => {
    initSystem()
  })
})

// Watch non-structural props for uniform updates (skip in debug mode)
$effect(() => {
  const _deps = [
    position,
    size,
    fadeSize,
    fadeOpacity,
    gravity,
    friction,
    speed,
    lifetime,
    direction,
    rotation,
    rotationSpeed,
    intensity,
    colorStart,
    colorEnd,
    collision,
    emitterShape,
    emitterRadius,
    emitterAngle,
    emitterHeight,
    emitterSurfaceOnly,
    emitterDirection,
    turbulence,
    startPosition,
    attractors,
    attractToCenter,
    startPositionAsDirection,
    softParticles,
    softDistance,
    orientAxis,
    stretchBySpeed,
    delay,
    emitCount,
  ]

  if (debug) return

  untrack(() => {
    if (!_system) return

    _system.setPosition(position as [number, number, number])
    _system.setDelay(delay)
    _system.setEmitCount(emitCount)
    _system.setTurbulenceSpeed(turbulence?.speed ?? 1)

    const normalized = normalizeProps({
      size,
      speed,
      fadeSize,
      fadeOpacity,
      lifetime,
      gravity,
      direction,
      startPosition,
      rotation,
      rotationSpeed,
      friction,
      intensity,
      colorStart,
      colorEnd,
      emitterShape,
      emitterRadius,
      emitterAngle,
      emitterHeight,
      emitterSurfaceOnly,
      emitterDirection,
      turbulence,
      attractors,
      attractToCenter,
      startPositionAsDirection,
      softParticles,
      softDistance,
      collision,
      orientAxis,
      stretchBySpeed,
    } as any)
    updateUniforms(_system.uniforms, normalized)
  })
})

// Frame loop
useTask((delta) => {
  if (!_system || !_system.initialized) return
  _system.update(delta)
  if (_emitting) {
    _system.autoEmit(delta)
  }
})

onMount(() => {
  mounted = true
  initSystem()
})

onDestroy(() => {
  mounted = false
  if (debug) {
    import('debug-vfx').then((mod) => {
      mod.destroyDebugPanel()
    })
  }
  destroySystem()
})

// Exposed API
export function spawn(
  x = 0,
  y = 0,
  z = 0,
  count = 20,
  overrides: Record<string, unknown> | null = null
) {
  if (!_system) return
  const [px, py, pz] = _system.position
  _system.spawn(px + x, py + y, pz + z, count, overrides)
}

export function start() {
  if (!_system) return
  _system.start()
  _emitting = true
}

export function stop() {
  if (!_system) return
  _system.stop()
  _emitting = false
}

export function clear() {
  _system?.clear()
}
</script>

{#if renderObjectForTemplate}
  <T is={renderObjectForTemplate} />
{/if}
